version: "3.8"

services:
    back-mysql:
        image: mysql
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=sensitive-field
        volumes:
            - type: bind
              source: ./db-data
              target: /var/lib/mysql
        ports:
            - "3306:3306"
